# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BXXVwSsJOCnb-lIK2k5L2CJM4zGFeb9-
"""

'''
CONDITONAL STATEMENTS

RULES:

   1. IF ELIF ELSE, you can do only if, else if one condition, and if multiple use elif.

   2. MAIN DIFFERENCE BETWEEN FOR AND WHILE
      FOR : multiple conditions can be assigned
      WHILE: a set loop that only breaks when the condition becomes false

    3. FUNCTIONS:
       def is the keyowrd or most of the times its also def__init__

'''

A=10

A

if 3==3:
    print('hi')

if 3==4:
    print('hi')

if 3==4:
    print('hi')
else:
    print('hello')

if 4==4:
    print('hi')
else:
    print('hello')

if 4>2:
    print('hi')
elif 6==6:
    print('hello')
elif 7==7:
    print('hey')
else:
    print('namste')

# loops

x = [3,2,67,9,34,678,90,33]

x

len(x)

x

type(x)

A

type(A)

x

x[0]

x[1]

for i in x:
    print(i)

x1 = [1,2,3,4,5,6]

x1

for i in x1:
    print(i**2)

3**3

x1

out = []
for i in x1:
    out.append(i**2)

type(out)

out

B=10

x

for i in x:
    print(i<10)

for i in x:
    if i<10:
        print(i)

out = []
for i in x1:
    out.append(i**2)

x1

t = [i for i in x1]

t

t1 = [i**3 for i in x1]

t1

x

t2 = [i**2 for i in x if i<10]

t2

i = 0
while i<5:
    print(i)
    i = i+1

def dodo(a):
    return a**2

dodo(8)

def dado(a,b):
    return a+b

dado(3,4)

def dado(a,b):
    '''
    this is funtion to add two numbers
    '''
    return a+b

dado(3,7)

s = "my name is dododo"

s

s.split()

s.split('is')

email = 'dododo@gmail.com'

email

email.split('@')

def uuu(email):
    return email.split('@')[0]

uuu('dododina@gmail.com')