# -*- coding: utf-8 -*-
"""SEABORN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tR4p9jVIO0Yc6jfSoqaGYGRG08-Qlsw0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

'''
RULES:
1. When you provide data, it should always be in the form of an array, only then
   will it become a dataframe.

2. When you plot any kind of graph you need to specify labels always
   like
   x='---',y='----', and data=testdata

3. During plotting a particular variable from the data set, you always specify the dataset
   like
   sns.displot(tips['total_bill'])

4. In some cases, you'll have to specify kind of graphs too.
   like
   kind='reg' or kind='hex'

 YOU'RE GOOD TO GO!

test=pd.DataFrame(np.array([[1,345],[2,600],[3,200],[4,900],[5,100]]),columns=['level','salary'])

test

sns.barplot(x='level',y='salary',data=test)
plt.show()

sns.scatterplot(x='level',y='salary',data=test)
plt.show()

tips=sns.load_dataset('tips')

tips

type(tips)

tips['total_bill']

sns.displot(tips['total_bill'])
plt.show

sns.distplot(tips['total_bill'])
plt.show

sns.distplot(tips['tip'])
plt.show

sns.histplot(tips['tip'])
plt.show

sns.jointplot(x='total_bill',y='tip',data=tips)

sns.jointplot(x='total_bill',y='tip',data=tips,kind='reg')

sns.jointplot(x='total_bill',y='tip',data=tips,kind='hex')

sns.pairplot(tips)

sns.pairplot(tips,hue='sex')

sns.pairplot(tips,hue='sex',palette='gist_rainbow')

sns.rugplot(tips['total_bill'])

sns.kdeplot(tips['total_bill'])

sns.countplot(x='sex',data=tips)

sns.boxplot(x='sex',y='total_bill',data=tips)

sns.violinplot(x='sex',y='total_bill',data=tips)

